apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-clone-app
  labels:
    app: youtube-clone-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: youtube-clone-app
  template:
    metadata:
      labels:
        app: youtube-clone-app
    spec:
      terminationGracePeriodSeconds: 
      containers:
      - name: youtube-clone-app
        image: /youtube-clone:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
